version: "3"

services:
  app:
    build: .
    command: "npm start"
    container_name: "app"
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

  db:
    image: postgres:alpine
    container_name: database
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    depends_on:
      - app
    volumes:
      - .:/usr/db
