version: "3"

services:
  app:
    build: .
    command: "npm start"
    container_name: "app"
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

  db:
    image: postgres
    container_name: database
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    depends_on:
      - app
    volumes:
      - .:/usr/db

  db-admin:
    image: dpage/pgadmin4
    container_name: database-admin
    restart: always
    ports:
      - "1000:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWD}
